<a href="https://colab.research.google.com/github/Aartizikre150/DAb300/blob/main/Practice_Questions_1_Solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Practice Questions : Week 2

1. Draw and label a single neuron and then code all the necessary mathematical operations to calculate the output of neuron using the following information:
     - $X = \left[4, 2, -1, 2 \right] $
     - $W = \left[1, 0, 2, 1\right]$
     - $b = [-4]$
     - sigmoid activation function


In [ ]:
import numpy as np

In [ ]:
x = np.array([4,2,-1,2])
w = np.array([1,0,2,1])
b = np.array([-4])

z = np.dot(w,x.T)+b.reshape(-1,1)
z

array([[0]])

In [ ]:
def sigmoid(z):
  a = 1/(1+np.exp(z))
  return a

In [ ]:
ans = sigmoid(z)
ans

array([[0.5]])

2. Draw and label the network and then code all the necessary mathematical operations to calculate the output of network for sample 2 given the following information:
     - $X = \left[\begin{array}{cc} 2 & -1 & 3 \\
     -4 & 1 & 2 \end{array}\right]$
     - $W^{[1]} = \left[\begin{array}{cc} 1 & 2 & 1 \\
     3 & 1 & 2 \end{array}\right]$
     - $b^{[1]} = [4, 2]$
     - $W^{[2]} = [1, 3]$
     - $b^{[2]} = [1]$
     - ReLU activation function

In [14]:
import numpy as np
class createmodel:
  def __init__(self, w1,w2,b1,b2):
    self.w1=w1
    self.w2=w2
    self.b1=b1.reshape(-1,1)
    self.b2=b2.reshape(-1,1)

  def activationfun(self,z):
    a=np.maximum(0,z)
    return a

  def function(self,X):
    z1 = np.dot(self.w1,X.T)+self.b1
    A1 = self.activationfun(z1)
    #print(A1)
    z2 = np.dot(self.w2,A1)+self.b2
    A2 = self.activationfun(z2)
    return A2

w1 = np.array([[1,2,1],[3,1,2]])
b1 = np.array([4,2])
w2 = np.array([1,3])
b2 = np.array([1])

network = createmodel(w1,w2,b1,b2)
x = np.array([[2,-1,3],[-4,1,2]])
network.function(x)

array([[47,  5]])

3. How many trainable parameters does the following network have:
 - Input data has 10 features
 - Layer 1 has 5 neurons
 - Layer 2 has 3 neurons
 - Output layer has 1 neuron

In [3]:
!pip install tensorflow

In [6]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(5, activation="relu",input_shape = (10,)),
    layers.Dense(3, activation="relu"),
    layers.Dense(1, activation="relu")
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 55        
                                                                 
 dense_1 (Dense)             (None, 3)                 18        
                                                                 
 dense_2 (Dense)             (None, 1)                 4         
                                                                 
Total params: 77 (308.00 Byte)
Trainable params: 77 (308.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
